language: cpp go

os:
  - linux

services:
  - docker

compiler:
  - gcc

matrix:
  include:
    - os: linux
      dist: focal

addons:
  apt:
    packages:
    - gcc-10
    - g++-10

before_script:
  - which gcc10 && export CC=gcc10 || true
  - which g++10 && export CXX=g++10 || true
  - which gcc-10 && export CC=gcc-10 || true
  - which g++-10 && export CXX=g++-10 || true

script:
  - go build
  - go test
